export const validCategories = [
  'Arts',
  'Arts>Design',
  'Arts>Fashion & Beauty',
  'Arts>Food',
  'Arts>Literature',
  'Arts>Performing Arts',
  'Arts>Visual Arts',
  'Business',
  'Business>Business News',
  'Business>Careers',
  'Business>Investing',
  'Business>Management & Marketing',
  'Business>Shopping',
  'Comedy',
  'Education',
  'Education>Higher Education',
  'Education>K-12',
  'Education>Language Courses',
  'Education>Training',
  'Games & Hobbies',
  'Games & Hobbies>Automotive',
  'Games & Hobbies>Aviation',
  'Games & Hobbies>Hobbies',
  'Games & Hobbies>Other Games',
  'Games & Hobbies>Video Games',
  'Government & Organizations',
  'Government & Organizations>Local',
  'Government & Organizations>National',
  'Government & Organizations>Non-Profit',
  'Government & Organizations>Regional',
  'Health',
  'Health>Alternative Health',
  'Health>Fitness & Nutrition',
  'Health>Kids & Family',
  'Health>Self-Help',
  'Health>Sexuality',
  'Music',
  'News & Politics',
  'Religion & Spirituality',
  'Religion & Spirituality>Buddhism',
  'Religion & Spirituality>Christianity',
  'Religion & Spirituality>Hinduism',
  'Religion & Spirituality>Islam',
  'Religion & Spirituality>Judaism',
  'Religion & Spirituality>Other',
  'Religion & Spirituality>Spirituality',
  'Science & Medicine',
  'Science & Medicine>Medicine',
  'Science & Medicine>Natural Sciences',
  'Science & Medicine>Social Sciences',
  'Society & Culture',
  'Society & Culture>History',
  'Society & Culture>Personal Journals',
  'Society & Culture>Philosophy',
  'Society & Culture>Places & Travel',
  'Sports & Recreation',
  'Sports & Recreation>Amateur',
  'Sports & Recreation>College & High School',
  'Sports & Recreation>Outdoor',
  'Sports & Recreation>Professional',
  'Sports & Recreation>TV & Film',
  'Technology',
  'Technology>Gadgets',
  'Technology>Podcasting',
  'Technology>Software How-To',
  'Technology>Tech News'
]
