export { authenticate } from 'middleware/auth/authenticate'
export { localAuth } from 'middleware/auth/localAuth'
export { emailNotExists, registerUser, validEmail } from 'middleware/auth/registerUser'
export { resetPassword, sendResetPassword } from 'middleware/auth/resetPassword'
export { sendVerification, verifyEmail } from 'middleware/auth/verification'
